### ISSUE TITLE
Java heap space error

### ISSUE THREAD

**Issue by NedaRR** [TIGRLab/admin#1154]
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
	at sun.font.GlyphList.ensureCapacity(Unknown Source)
	at sun.font.GlyphList.setFromChars(Unknown Source)
	at sun.java2d.pipe.GlyphListPipe.drawChars(Unknown Source)
	at sun.java2d.SunGraphics2D.drawChars(Unknown Source)
	at org.netbeans.editor.DrawGraphics$GraphicsDG.flush(DrawGraphics.java:633)
	at org.netbeans.editor.DrawGraphics$GraphicsDG.flush(DrawGraphics.java:522)
	at org.netbeans.editor.DrawGraphics$GraphicsDG.setBuffer(DrawGraphics.java:756)
	at org.netbeans.editor.DrawEngine.draw(DrawEngine.java:1116)
	at org.netbeans.editor.DrawEngineLineView.paint(DrawEngineLineView.java:233)
	at org.netbeans.lib.editor.view.GapBoxViewChildren.paintChildren(GapBoxViewChildren.java:783)
	at org.netbeans.lib.editor.view.GapBoxView.paint(GapBoxView.java:1463)
	at org.netbeans.lib.editor.view.GapDocumentView.paint(GapDocumentView.java:231)
	at org.netbeans.editor.DrawEngineDocView.paint(DrawEngineDocView.java:314)
	at org.netbeans.editor.view.spi.LockView.paint(LockView.java:363)
	at javax.swing.plaf.basic.BasicTextUI$RootView.paint(Unknown Source)
	at javax.swing.plaf.basic.BasicTextUI.paintSafely(Unknown Source)
	at javax.swing.plaf.basic.BasicTextUI.paint(Unknown Source)
	at javax.swing.plaf.basic.BasicTextUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JViewport.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
	at sun.font.GlyphList.ensureCapacity(Unknown Source)
	at sun.font.GlyphList.setFromChars(Unknown Source)
	at sun.java2d.pipe.GlyphListPipe.drawChars(Unknown Source)
	at sun.java2d.SunGraphics2D.drawChars(Unknown Source)
	at org.netbeans.editor.DrawGraphics$GraphicsDG.flush(DrawGraphics.java:633)
	at org.netbeans.editor.DrawGraphics$GraphicsDG.flush(DrawGraphics.java:522)
	at org.netbeans.editor.DrawGraphics$GraphicsDG.setBuffer(DrawGraphics.java:756)
	at org.netbeans.editor.DrawEngine.draw(DrawEngine.java:1116)
	at org.netbeans.editor.DrawEngineLineView.paint(DrawEngineLineView.java:233)
	at org.netbeans.lib.editor.view.GapBoxViewChildren.paintChildren(GapBoxViewChildren.java:783)
	at org.netbeans.lib.editor.view.GapBoxView.paint(GapBoxView.java:1463)
	at org.netbeans.lib.editor.view.GapDocumentView.paint(GapDocumentView.java:231)
	at org.netbeans.editor.DrawEngineDocView.paint(DrawEngineDocView.java:314)
	at org.netbeans.editor.view.spi.LockView.paint(LockView.java:363)
	at javax.swing.plaf.basic.BasicTextUI$RootView.paint(Unknown Source)
	at javax.swing.plaf.basic.BasicTextUI.paintSafely(Unknown Source)
	at javax.swing.plaf.basic.BasicTextUI.paint(Unknown Source)
	at javax.swing.plaf.basic.BasicTextUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JViewport.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.BufferStrategyPaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)

**Comment by josephdviviano** [comment]
looking at this now

**Comment by josephdviviano** [comment]
try running 

`matlab -Xmx2048m`
