### ISSUE TITLE
kimsrv can't be ansibled

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#176]
errors suggest 'no space left on device'

    TASK: [workstation | software installed] ************************************** 
    failed: [kimsrv] => (item=unattended-upgrades,screen,tmux,intel-microcode,synaptic,git,cvs,subversion,google-talkplugin,skype,imagej,imagemagick,speedcrunch,openssh-server,build-essential,google-chrome-stable,texlive-full,inkscape,gimp,environment-modules,vim,emacs,parallel,htop,mutt,abook,nvidia-331-updates,nvidia-cuda-toolkit,virtualbox-4.3,axel,zip,rar,unrar,unace,gnuplot-qt,gle-graphics,firefox,octave,iotop,ubuntu-restricted-extras,texstudio,gparted,libreoffice,libreoffice-help-en-us,ansible,thunderbird,vlc,gnome-terminal,numlockx,gfortran,dcmtk,python-pip,libapparmor1,python-dev,libsqlite3-dev,sqlite3,pspp,nedit,quota,thermald,protobuf-c-compiler,protobuf-compiler,python-protobuf,arandr,parcellite,remmina,pass,pinentry-curses,gedit,icedtea-plugin,fslview,fslview-doc,dc,libcr0,libgdchart-gd2-noxpm,libgiftiio0,libhwloc5,libibverbs1,libnetcdfc++4,libnetcdfc7,libnewmat10ldbl,libnifti2,libopenmpi1.6,libpq5,libqt4-designer,libqt4-qt3support,libqwt5-qt4,libtorque2,libvtk5.8,libvtk5.8-qt4,qt-assistant-compat,tcsh,g++,cmake,cmake-curses-gui,bison,flex,freeglut3,freeglut3-dev,libxi6,libxi-dev,libxmu6,libxmu-dev,libxmu-headers,gfortran,libreadline-dev,libcairo-dev,openjdk-7-jdk,libxml2-dev,automake,autoconf,libtool,libblas-dev,liblapack-dev,libnetpbm10-dev,libxss1,libpcre++0,libcoin80,libjpeg62,libtk8.5,terminator,geany,geany-plugins,geany-plugin-markdown,geany-common,x2goclient,x2goserver,x2goserver-xsession,x2golxdebindings,krita,kritasketch,kdelibs-bin,oxygen-icon-theme,liblapack3gf,libatlas3gf-base,libgeos-3.4.2,libgeos-c1,libgeos-doc,libgeos-dev,xubuntu-default-settings,xubuntu-desktop,xubuntu-icon-theme,xubuntu-default-settings,xubuntu-artwork,xubuntu-wallpapers,xfswitch-plugin,gnome-screensaver,libboost-thread-dev,libgetopt-tabular-perl) => {"failed": true, "item": "unattended-upgrades,screen,tmux,intel-microcode,synaptic,git,cvs,subversion,google-talkplugin,skype,imagej,imagemagick,speedcrunch,openssh-server,build-essential,google-chrome-stable,texlive-full,inkscape,gimp,environment-modules,vim,emacs,parallel,htop,mutt,abook,nvidia-331-updates,nvidia-cuda-toolkit,virtualbox-4.3,axel,zip,rar,unrar,unace,gnuplot-qt,gle-graphics,firefox,octave,iotop,ubuntu-restricted-extras,texstudio,gparted,libreoffice,libreoffice-help-en-us,ansible,thunderbird,vlc,gnome-terminal,numlockx,gfortran,dcmtk,python-pip,libapparmor1,python-dev,libsqlite3-dev,sqlite3,pspp,nedit,quota,thermald,protobuf-c-compiler,protobuf-compiler,python-protobuf,arandr,parcellite,remmina,pass,pinentry-curses,gedit,icedtea-plugin,fslview,fslview-doc,dc,libcr0,libgdchart-gd2-noxpm,libgiftiio0,libhwloc5,libibverbs1,libnetcdfc++4,libnetcdfc7,libnewmat10ldbl,libnifti2,libopenmpi1.6,libpq5,libqt4-designer,libqt4-qt3support,libqwt5-qt4,libtorque2,libvtk5.8,libvtk5.8-qt4,qt-assistant-compat,tcsh,g++,cmake,cmake-curses-gui,bison,flex,freeglut3,freeglut3-dev,libxi6,libxi-dev,libxmu6,libxmu-dev,libxmu-headers,gfortran,libreadline-dev,libcairo-dev,openjdk-7-jdk,libxml2-dev,automake,autoconf,libtool,libblas-dev,liblapack-dev,libnetpbm10-dev,libxss1,libpcre++0,libcoin80,libjpeg62,libtk8.5,terminator,geany,geany-plugins,geany-plugin-markdown,geany-common,x2goclient,x2goserver,x2goserver-xsession,x2golxdebindings,krita,kritasketch,kdelibs-bin,oxygen-icon-theme,liblapack3gf,libatlas3gf-base,libgeos-3.4.2,libgeos-c1,libgeos-doc,libgeos-dev,xubuntu-default-settings,xubuntu-desktop,xubuntu-icon-theme,xubuntu-default-settings,xubuntu-artwork,xubuntu-wallpapers,xfswitch-plugin,gnome-screensaver,libboost-thread-dev,libgetopt-tabular-perl"}
    stderr: Committing to: /etc/
    modified .etckeeper
    modified bash.bashrc
    modified apt/sources.list
    modified apt/trusted.gpg
    added apt/preferences.d/xorg-edgers-pin-400
    added apt/sources.list.d/archive_canonical_com_ubuntu.list
    added apt/sources.list.d/dl_google_com_linux_chrome_deb.list
    added apt/sources.list.d/dl_google_com_linux_talkplugin_deb.list
    added apt/sources.list.d/download_mendeley_com_apt.list
    added apt/sources.list.d/download_virtualbox_org_virtualbox_debian.list
    added apt/sources.list.d/neuro_debian_net_debian.list
    added apt/sources.list.d/ppa_ansible_ansible_trusty.list
    added apt/sources.list.d/ppa_blahota_texstudio_trusty.list
    added apt/sources.list.d/ppa_inkscape_dev_stable_trusty.list
    added apt/sources.list.d/ppa_kubuntu_ppa_backports_trusty.list
    added apt/sources.list.d/ppa_launchpad_net_webupd8team_atom_ubuntu.list
    added apt/sources.list.d/ppa_libreoffice_ppa_trusty.list
    added apt/sources.list.d/ppa_otto_kesselgulasch_gimp_trusty.list
    added apt/sources.list.d/ppa_ubuntu_x_swat_x_updates_trusty.list
    added apt/sources.list.d/ppa_x2go_stable_trusty.list
    added profile.d/quarantine.sh
    Committed revision 76.
    Extracting templates from packages: 100%
    dpkg: gnuplot-nox: dependency problems, but removing anyway as you requested:
     gnuplot depends on gnuplot-nox | gnuplot-x11 | gnuplot-qt; however:
      Package gnuplot-nox is to be removed.
      Package gnuplot-x11 is not installed.
      Package gnuplot-qt is not installed.

    mscorefonts-eula license could not be presented
    try 'dpkg-reconfigure debconf' to select a frontend other than noninteractive

    /usr/bin/mandb: can't write to /var/cache/man/32630: No space left on device

    (gconftool-2:32762): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
    Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
    dpkg: error processing archive /var/cache/apt/archives/app-install-data_14.04.1_all.deb (--unpack):
     cannot copy extracted data for './usr/share/app-install/icons/eBook-speaker.svgz' to '/usr/share/app-install/icons/eBook-speaker.svgz.dpkg-new': failed to write (No space left on device)
    No apport report written because the error message indicates a disk full error
    dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
    dpkg: error processing archive /var/cache/apt/archives/xterm_297-1ubuntu1_amd64.deb (--unpack):
     cannot copy extracted data for './usr/share/doc/xterm/README.i18n.gz' to '/usr/share/doc/xterm/README.i18n.gz.dpkg-new': failed to write (No space left on device)
    No apport report written because the error message indicates a disk full error
    dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
    dpkg: error processing archive /var/cache/apt/archives/gnome-terminal-data_3.6.2-0ubuntu1_all.deb (--unpack):
     cannot copy extracted data for './usr/share/gconf/schemas/gnome-terminal.schemas' to '/usr/share/gconf/schemas/gnome-terminal.schemas.dpkg-new': failed to write (No space left on device)
    No apport report written because the error message indicates a disk full error
    dpkg: error processing archive /var/cache/apt/archives/apt-offline_1.3.1ubuntu0.1_all.deb (--unpack):
     cannot copy extracted data for './usr/share/pyshared/apt_offline_core/AptOffline_argparse.py' to '/usr/share/pyshared/apt_offline_core/AptOffline_argparse.py.dpkg-new': failed to write (No space left on device)
    No apport report written because MaxReports is reached already
    dpkg: error processing archive /var/cache/apt/archives/x11-xserver-utils_7.7+2ubuntu1_amd64.deb (--unpack):
     cannot copy extracted data for './usr/share/doc/x11-xserver-utils/copyright' to '/usr/share/doc/x11-xserver-utils/copyright.dpkg-new': failed to write (No space left on device)
    No apport report written because MaxReports is reached already
    dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
    dpkg: error processing archive /var/cache/apt/archives/arandr_0.1.7.1-1_all.deb (--unpack):
     cannot copy extracted data for './usr/share/pyshared/screenlayout/auxiliary.py' to '/usr/share/pyshared/screenlayout/auxiliary.py.dpkg-new': failed to write (No space left on device)
    No apport report written because MaxReports is reached already
    tar: ./control: Cannot write: No space left on device
    tar: ./prerm: Cannot write: No space left on device
    tar: Exiting with failure status due to previous errors
    dpkg-deb: error: subprocess tar returned error exit status 2
    dpkg: error processing archive /var/cache/apt/archives/avahi-autoipd_0.6.31-4ubuntu1_amd64.deb (--unpack):
     subprocess dpkg-deb --control returned error exit status 2
    No apport report written because MaxReports is reached already
    dpkg: error processing archive /var/cache/apt/archives/avahi-utils_0.6.31-4ubuntu1_amd64.deb (--unpack):
     cannot copy extracted data for './usr/share/man/man1/avahi-publish.1.gz' to '/usr/share/man/man1/avahi-publish.1.gz.dpkg-new': failed to write (No space left on device)
    No apport report written because MaxReports is reached already
    dpkg: error processing archive /var/cache/apt/archives/axel_2.4-1_amd64.deb (--unpack):
     cannot copy extracted data for './usr/bin/axel' to '/usr/bin/axel.dpkg-new': failed to write (No space left on device)
    No apport report written because MaxReports is reached already
    dpkg: error processing archive /var/cache/apt/archives/libbison-dev_2%3a3.0.2.dfsg-2_amd64.deb (--unpack):
     cannot copy extracted data for './usr/share/doc/libbison-dev/TODO.gz' to '/usr/share/doc/libbison-dev/TODO.gz.dpkg-new': failed to write (No space left on device)
    No apport report written because MaxReports is reached already
    dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
    tar: ./postinst: Cannot write: No space left on device
    tar: ./md5sums: Cannot write: No space left on device
    tar: ./preinst: Cannot write: No space left on device
    tar: Exiting with failure status due to previous errors
    dpkg-deb: error: subprocess tar returned error exit status 2
    dpkg: error processing archive /var/cache/apt/archives/bison_2%3a3.0.2.dfsg-2_amd64.deb (--unpack):
     subprocess dpkg-deb --control returned error exit status 2
    No apport report written because MaxReports is reached already
    tar: ./md5sums: Cannot write: No space left on device
    tar: ./control: Cannot write: No space left on device
    tar: ./prerm: Cannot write: No space left on device
    tar: ./postrm: Cannot write: No space left on device
    tar: ./preinst: Cannot write: No space left on device
    tar: Exiting with failure status due to previous errors
    dpkg-deb: error: subprocess tar returned error exit status 2
    dpkg: error processing archive /var/cache/apt/archives/bluez_4.101-0ubuntu13.1_amd64.deb (--unpack):
     subprocess dpkg-deb --control returned error exit status 2
    No apport report written because MaxReports is reached already
    tar: ./control: Cannot write: No space left on device
    tar: ./md5sums: Cannot write: No space left on device
    tar: ./postrm: Cannot write: No space left on device
    tar: Exiting with failure status due to previous errors
    dpkg-deb: error: subprocess tar returned error exit status 2
    dpkg: error processing archive /var/cache/apt/archives/libopenobex1_1.5-2.1_amd64.deb (--unpack):
     subprocess dpkg-deb --control returned error exit status 2
    No apport report written because MaxReports is reached already
    tar: ./conffiles: Cannot write: No space left on device
    tar: Exiting with failure status due to previous errors
    dpkg-deb: error: subprocess tar returned error exit status 2
    dpkg: error processing archive /var/cache/apt/archives/obex-data-server_0.4.6-0ubuntu2_amd64.deb (--unpack):
     subprocess dpkg-deb --control returned error exit status 2
    No apport report written because MaxReports is reached already
    tar: ./prerm: Cannot write: No space left on device
    tar: ./md5sums: Cannot write: No space left on device
    tar: Exiting with failure status due to previous errors
    dpkg-deb: error: subprocess tar returned error exit status 2
    dpkg: error processing archive /var/cache/apt/archives/python-notify_0.1.1-3ubuntu2_amd64.deb (--unpack):
     subprocess dpkg-deb --control returned error exit status 2
    No apport report written because MaxReports is reached already
    tar: ./conffiles: Cannot write: No space left on device
    tar: Exiting with failure status due to previous errors
    dpkg-deb: error: subprocess tar returned error exit status 2
    dpkg: error processing archive /var/cache/apt/archives/notification-daemon_0.7.6-1_amd64.deb (--unpack):
     subprocess dpkg-deb --control returned error exit status 2
    No apport report written because MaxReports is reached already
    tar: ./md5sums: Wrote only 4096 of 4774 bytes
    tar: Exiting with failure status due to previous errors
    dpkg-deb: error: subprocess tar returned error exit status 2
    dpkg: error processing archive /var/cache/apt/archives/xfce4-notifyd_0.2.4-2_amd64.deb (--unpack):
     subprocess dpkg-deb --control returned error exit status 2
    No apport report written because MaxReports is reached already
    tar: ./prerm: Cannot write: No space left on device
    tar: ./postrm: Cannot write: No space left on device
    tar: ./postinst: Cannot write: No space left on device
    tar: ./md5sums: Cannot write: No space left on device
    tar: Exiting with failure status due to previous errors
    dpkg-deb: error: subprocess tar returned error exit status 2
    dpkg: error processing archive /var/cache/apt/archives/blueman_1.23-git201403102151-1ubuntu1_amd64.deb (--unpack):
     subprocess dpkg-deb --control returned error exit status 2
    No apport report written because MaxReports is reached already
    dpkg: error processing archive /var/cache/apt/archives/bluez-alsa_4.101-0ubuntu13.1_amd64.deb (--unpack):
     cannot copy extracted data for './usr/share/doc/bluez-alsa/copyright' to '/usr/share/doc/bluez-alsa/copyright.dpkg-new': failed to write (No space left on device)
    No apport report written because MaxReports is reached already
    dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
    dpkg: unrecoverable fatal error, aborting:
     unable to flush /var/lib/dpkg/updates/tmp.i after padding: No space left on device
    Traceback (most recent call last):
      File "/usr/bin/bzr", line 117, in <module>
        exit_val = bzrlib.commands.main()
      File "/usr/lib/python2.7/dist-packages/bzrlib/commands.py", line 1206, in main
        ret = run_bzr_catch_errors(argv)
      File "/usr/lib/python2.7/dist-packages/bzrlib/commands.py", line 1219, in run_bzr_catch_errors
        return exception_to_return_code(run_bzr, argv)
      File "/usr/lib/python2.7/dist-packages/bzrlib/commands.py", line 935, in exception_to_return_code
        exitcode = trace.report_exception(exc_info, sys.stderr)
      File "/usr/lib/python2.7/dist-packages/bzrlib/trace.py", line 482, in report_exception
        log_exception_quietly()
      File "/usr/lib/python2.7/dist-packages/bzrlib/trace.py", line 361, in log_exception_quietly
        mutter(traceback.format_exc())
      File "/usr/lib/python2.7/dist-packages/bzrlib/trace.py", line 161, in mutter
        _trace_file.write(out)
    IOError: [Errno 28] No space left on device
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 139, in apport_excepthook
        pr.write(f)
      File "/usr/lib/python2.7/dist-packages/problem_report.py", line 321, in write
        file.write(v.replace(b'\n', b'\n '))
    IOError: [Errno 28] No space left on device

**Comment by josephdviviano** [comment]
jdv@kimsrv:/projects/IT/ansible/ansible-playbooks$ df -h 
    Filesystem                   Size  Used Avail Use% Mounted on
    /dev/mapper/vg_root-lv_root   14G   14G     0 100% /

**Comment by josephdviviano** [comment]
I removed a bunch of stuff from 

    /var/cache/apt/archives

to get us back to normal. However we still can't ansible this thing yet.

**Comment by josephdviviano** [comment]
I'm building an ansible role called 'computenode' that is similar to workstation, but contains no GUI software. This keeps the install small. We can use this on future machines we want to transform into a compute node (as planned in our CFI).

**Comment by josephdviviano** [comment]
compute node role now exists in ansible.
