### ISSUE TITLE
Weird Error from check-headers STOPPD

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#320]
Traceback (most recent call last):
  File "/archive/data-2.0/code/datman/bin/xnat-extract.py", line 401, in <module>
    main()
  File "/archive/data-2.0/code/datman/bin/xnat-extract.py", line 184, in main
    extract_archive(exportinfo, archivepath, datadir, blacklist)
  File "/archive/data-2.0/code/datman/bin/xnat-extract.py", line 230, in extract_archive
    exportdir, blacklist)
  File "/archive/data-2.0/code/datman/bin/xnat-extract.py", line 241, in export_series
    mangled_descr = dm.utils.mangle(description)
  File "/archive/data-2.0/code/datman/datman/utils.py", line 79, in mangle
    return re.sub(r"[^a-zA-Z0-9.+]+","-",string)
  File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
ERROR: /mnt/xnat/spred/archive/STOPPD04/arc001/360006 folder is not named according to the data naming policy. Skipping

**Comment by pipitone** [comment]
Nothing weird about this. It's complaining that the scan name doesn't follow our convention of `STUDY_SITE_SUBJECT_SESSION_REPEAT`.
