### ISSUE TITLE
qc phantoms errors

### ISSUE THREAD

**Issue by edickie** [TIGRLab/admin#321]
++ 3daxialize: AFNI version=AFNI_2011_12_21_1014 (Dec 10 2014) [64-bit]

Final result:
1.002792 -0.000284 -0.007179 18.045260
0.000258 1.000620 -0.003109 -21.920600
0.007827 0.003411 1.000513 -1.385963
0.000000 0.000000 0.000000 1.000000

++ 3daxialize: AFNI version=AFNI_2011_12_21_1014 (Dec 10 2014) [64-bit]
** AFNI converts NIFTI_datatype=4 (INT16) in file /archive/data-2.0/PRELAPSE/data/nii/PRE01_TXS_PHA_ADN0007/PRE01_TXS_PHA_ADN0007_T1_401_3D-T1-PRE.nii.gz to FLOAT32
     Warnings of this type will be muted for this session.
     Set AFNI_NIFTI_TYPE_WARN to YES to see them all, NO to see none.

Final result:
1.014330 -0.002798 -0.044973 16.915810
0.007610 0.996328 0.061856 -27.758211
0.041074 -0.062541 1.002429 0.458941
0.000000 0.000000 0.000000 1.000000

Traceback (most recent call last):
  File "/archive/data-2.0/code/datman/bin/qc-phantom.py", line 745, in <module>
    main()
  File "/archive/data-2.0/code/datman/bin/qc-phantom.py", line 739, in main
    main_adni(project, sites, int(ntp), assets)
  File "/archive/data-2.0/code/datman/bin/qc-phantom.py", line 488, in main_adni
    os.path.join(data_path, 'nii', subj, phantom), assets)
  File "/archive/data-2.0/code/datman/bin/qc-phantom.py", line 235, in find_adni_t1_vals
    labels = random_walker(data, markers, beta=10, mode='bf')
  File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/site-packages/skimage/segmentation/random_walker_segmentation.py", line 384, in random_walker
    data = np.atleast_3d(img_as_float(data))[..., np.newaxis]
  File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/site-packages/skimage/util/dtype.py", line 287, in img_as_float
    return convert(image, np.float64, force_copy)
  File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/site-packages/skimage/util/dtype.py", line 191, in convert
    raise ValueError("Images of type float must be between -1 and 1.")
ValueError: Images of type float must be between -1 and 1.

**Comment by josephdviviano** [comment]
OK -- I've pushed some changes to the code that should make the ADNI segmenting robust to a single bad scan. We've also fixed the renaming issue ... let's see if it pops up in the run script again!

**Comment by josephdviviano** [comment]
Is this resolved?
