### ISSUE TITLE
empty subjects in DTI15T nii/ folder

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#784]
- DTI_TGH_S097_01
- DTI_TGH_S107_01
- DTI_TGH_S144_01
- DTI_TGH_S171_01

**Comment by edickie** [comment]
Have some of these been blacklisted?

**Comment by josephdviviano** [comment]
Why would someone blacklist an entire subject?

**Comment by josephdviviano** [comment]
I tried running `dm2-xnat-extract.py -q DTI15T` last night and I found this:

```
...
ERROR:/archive/code/datman/bin/dm2-xnat-extract.py:An error happened exporting nii from scan:DTI_TGH_H065_01_01
Traceback (most recent call last):
  File "/archive/code/datman/bin/dm2-xnat-extract.py", line 483, in process_scans
    exporter(src_dir, target_dir, file_stem)
  File "/archive/code/datman/bin/dm2-xnat-extract.py", line 627, in export_nii_command
    .format(tmpdir, seriesdir), DRYRUN)
  File "/archive/code/datman/datman/utils.py", line 470, in run
    p = proc.Popen(cmd, shell=True, stdout=proc.PIPE, stderr=proc.PIPE)
  File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/subprocess.py", line 1223, in _execute_child
    errpipe_read, errpipe_write = self.pipe_cloexec()
  File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/subprocess.py", line 1175, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files
2016-11-29 20:47:36,102 - /archive/code/datman/bin/dm2-xnat-extract.py - ERROR - An error happened exporting nii from scan:DTI_TGH_H065_01_01
Traceback (most recent call last):
  File "/archive/code/datman/bin/dm2-xnat-extract.py", line 483, in process_scans
    exporter(src_dir, target_dir, file_stem)
  File "/archive/code/datman/bin/dm2-xnat-extract.py", line 627, in export_nii_command
    .format(tmpdir, seriesdir), DRYRUN)
  File "/archive/code/datman/datman/utils.py", line 470, in run
    p = proc.Popen(cmd, shell=True, stdout=proc.PIPE, stderr=proc.PIPE)
  File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/subprocess.py", line 702, in __init__
    errread, errwrite), to_close = self._get_handles(stdin, stdout, stderr)
  File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/subprocess.py", line 1141, in _get_handles
    errread, errwrite = self.pipe_cloexec()
  File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/subprocess.py", line 1175, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files
ERROR:/archive/code/datman/bin/dm2-xnat-extract.py:An error happened exporting nii from scan:DTI_TGH_H065_01_01
Traceback (most recent call last):
  File "/archive/code/datman/bin/dm2-xnat-extract.py", line 483, in process_scans
    exporter(src_dir, target_dir, file_stem)
  File "/archive/code/datman/bin/dm2-xnat-extract.py", line 627, in export_nii_command
    .format(tmpdir, seriesdir), DRYRUN)
  File "/archive/code/datman/datman/utils.py", line 470, in run
    p = proc.Popen(cmd, shell=True, stdout=proc.PIPE, stderr=proc.PIPE)
  File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/subprocess.py", line 702, in __init__
    errread, errwrite), to_close = self._get_handles(stdin, stdout, stderr)
  File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/subprocess.py", line 1141, in _get_handles
    errread, errwrite = self.pipe_cloexec()
  File "/opt/quarantine/python/2.7.9-anaconda-2.1.0-150119/build/lib/python2.7/subprocess.py", line 1175, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/archive/code/datman/bin/dm2-xnat-extract.py", line 714, in <module>
  File "/archive/code/datman/bin/dm2-xnat-extract.py", line 205, in main
  File "/archive/code/datman/bin/dm2-xnat-extract.py", line 276, in process_session
  File "/archive/code/datman/bin/dm2-xnat-extract.py", line 431, in process_scans
  File "/archive/code/datman/datman/dashboard.py", line 166, in get_add_scan
  File "/archive/code/datman/datman/dashboard.py", line 108, in get_add_session
  File "/archive/code/datman/datman/utils.py", line 57, in check_checklist
  File "/archive/code/datman/datman/config.py", line 33, in __init__
  File "/archive/code/datman/datman/config.py", line 54, in load_yaml
IOError: [Errno 24] Too many open files: '/archive/code/config/tigrlab_config.yaml'
```

**Comment by josephdviviano** [comment]
OK those errors seem to be fixed. First two subjects are there, but we have suspiciously few outputs for the later subjects:

+ DTI_TGH_S144_01
+ DTI_TGH_S171_01

**Comment by josephdviviano** [comment]
Looks like I'm wrong -- even the earliest data only has a T1 and a PD scan...
