### ISSUE TITLE
header check should fail gracefully in dm-qc-report.py

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#830]
bject SPN01_MRP_0073_01 --rewrite
Traceback (most recent call last):
  File "/archive/code/datman/bin/dm-qc-report.py", line 624, in <module>
    main()
  File "/archive/code/datman/bin/dm-qc-report.py", line 560, in main
    report_name = qc_subject(path, scanid, config)
  File "/archive/code/datman/bin/dm-qc-report.py", line 516, in qc_subject
    add_header_qc(fname, report, headerDiff)
  File "/archive/code/datman/bin/dm-qc-report.py", line 237, in add_header_qc
    with open(logdata, 'r') as f:
IOError: [Errno 2] No such file or directory: '/archive/data/SPINS/qc/SPN01_MRP_0073_01/header-diff.log'

**Comment by DESm1th** [comment]
I've added a fix for this, but I haven't pushed my local copy yet. I've added a bunch of small bug fixes, but don't want to push until I've finished writing tests to ensure I haven't accidentally broken things in the process.

**Comment by josephdviviano** [comment]
Well, you win!

**Comment by DESm1th** [comment]
Ok, I pushed my changes to our repo. I'm not finished testing the whole script, so hopefully I didn't bork something else unintentionally. When I ran it just now though, it seemed ok.
